### PR TITLE
Use sha256 instead of sha1

### LINKED ISSUE #3: Homebrew complaing that use of SHA1 is deprecated
```
Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/karan/homebrew-karan/Formula/gitignore.rb:10:in `block in <class:Gitignore>'
Please report this to the karan/karan tap!
```

### PR DESCRIPTION
**Pull request by youtux**
Fixes #3

### CODE REVIEW

**Comment by wo0dyn** [comment]
@karan Any news about this PR?

**Comment by karan** [comment]
This is out of date. `joe` is distributed as a standalone binary.

**Comment by youtux** [comment]
Honestly, I don't see the reason why you want to remove the homebrew formula, since you still can build joe from source.

**Comment by karan** [comment]
Mostly because it's more work for me

**Pull request closed without merging**
