### PR TITLE
Change formula name and better test

### PR DESCRIPTION
**Pull request by youtux**

### CODE REVIEW

**Comment by karan** [comment]
What is the rationale behind renaming the formula?

**Comment by youtux** [comment]
In my opinion, it is counterintuitive to type `brew install gitignore` when I want to install `joe`. To me it makes more sense to type `brew install joe-python`. Also, what would happen when somebody makes and distribute a tool called `gitignore`?

**Comment by karan** [comment]
I think it would be up to them to find a new name for it. But I can see the point.

Personally, I do not like hyphens in names. Also, a user does not care what language a tool is written in. `joe-python` suggest that it's a python module. How about `joecli`?

**Comment by youtux** [comment]
Well, my proposal `joe-python` was just to disambiguate it. Hyphens are widely used for formulae names in brew, as there are (at the moment of writing) 890 formulae with hyphens over 3662 formulae in total. 
You proposed `joecli`. What if one day you implement a GUI or a web interface? :)

All things considerated, I would propose `joe-gitignore`.

**Comment by karan** [comment]
> What if one day you implement a GUI or a web interface? 

That won't happen. :)

I'll leave this PR open in case someone else has any opinions or suggestions. For the time being, I'll leave the name unchanged.

Thanks for starting this discussion though!

**Comment by youtux** [comment]
Well, maybe you like http://runnable.com/VLsp2_dWQZAKoOvF/joe_from_flask-for-python and you decide to include it :)

**Comment by karan** [comment]
Not sure I understand what you mean. But `joe` by itself will remain an API, others are free to build on top of it.

**Comment by youtux** [comment]
I just wanted to state that `joecli` would be inconsistent in the case you decide to implement another kind of UI on top of `joe`, and I linked you a simple web interface made by juanpablo.

But since joe will remain an API I think `joecli` could be an appropriate choice. Although the final decision is yours of course :)

**Pull request closed without merging**
